
# This is a Terragrunt module generated by boilerplate.
terraform {
  source = "git::https://github.com/rstuhlmuller/terragrunt-catalog.git//modules/kubernetes_namespace?ref=${values.version}"
}

include "root" {
  path = find_in_parent_folders("root.hcl")
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: The name of the namespace
  # Type: string
  name = values.name # TODO: fill in value


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: The labels of the namespace
  # Type: map
  labels = try(values.labels, {})

  # Description: The annotations of the namespace
  # Type: map
  annotations = try(values.annotations, {})

  # Description: The generate name of the namespace
  # Type: string
  generate_name = try(values.generate_name, null)

  # Description: The tags of the namespace
  # Type: map
  tags = try(values.tags, {})
}
