
# This is a Terragrunt module generated by boilerplate.
terraform {
  source = "git::https://github.com/rstuhlmuller/terragrunt-catalog.git//modules/kubernets_external_secret?ref=${values.version}"
}

include "root" {
  path = find_in_parent_folders("root.hcl")
}

dependency "kubernetes_namespace" {
  config_path = values.namespace_config_path
  mock_outputs = {
    namespace = "namespace-name"
  }
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: The secrets to create
  # Type: list
  secrets = values.secrets # TODO: fill in value

  # Description: The namespace to create the secrets in
  # Type: string
  namespace = dependency.kubernetes_namespace.outputs.name # TODO: fill in value

  # Description: The name of the secret
  # Type: string
  secret_name = values.secret_name # TODO: fill in value


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: The refresh policy for the secret
  # Type: string
  refresh_policy = try(values.refresh_policy, "OnChange")

  # Description: The description of the secret
  # Type: string
  description = try(values.description, "Kubernetes External Secret")

}
