include "root" {
  path = find_in_parent_folders("root.hcl")
}

# This is a Terragrunt module generated by boilerplate.
terraform {
  source = "git::https://github.com/rstuhlmuller/terragrunt-catalog.git//modules/argocd_application?ref=${values.version}"
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: (variable namespace did not define a description)
  # Type: string
  namespace = values.namespace # TODO: fill in value

  # Description: (variable repo_url did not define a description)
  # Type: string
  repo_url = values.repo_url # TODO: fill in value


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: (variable tags did not define a description)
  # Type: map
  tags = try(values.tags, {})

  # Description: (variable labels did not define a description)
  # Type: map
  labels = try(values.labels, {})

  # Description: (variable annotations did not define a description)
  # Type: map
  annotations = try(values.annotations, {})

  # Description: (variable project did not define a description)
  # Type: string
  project = try(values.project, "default")

  # Description: (variable server did not define a description)
  # Type: string
  server = try(values.server, "https://kubernetes.default.svc")

  # Description: (variable target_revision did not define a description)
  # Type: string
  target_revision = try(values.target_revision, "HEAD")

  # Description: (variable path did not define a description)
  # Type: string
  path = try(values.path, null)

  # Description: (variable chart did not define a description)
  # Type: string
  chart = try(values.chart, null)

  # Description: (variable helm_parameters did not define a description)
  # Type: list
  helm_parameters = try(values.helm_parameters, [])

  # Description: (variable helm_values did not define a description)
  # Type: string
  helm_values = try(values.helm_values, null)

  # Description: (variable automated_sync_policy did not define a description)
  # Type: object
  automated_sync_policy = try(values.automated_sync_policy, null)
}
