
# This is a Terragrunt module generated by boilerplate.
terraform {
  source = "git::https://github.com/rstuhlmuller/terragrunt-catalog.git//modules/helm_release?ref=${values.version}"
}

include "root" {
  path = find_in_parent_folders("root.hcl")
}

dependency "kubernetes_namespace" {
  config_path = values.namespace_config_path
  mock_outputs = {
    namespace = "namespace-name"
  }
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: The name of the namespace to install the helm chart in
  # Type: string
  namespace = dependency.kubernetes_namespace.outputs.name # TODO: fill in value

  # Description: The name of the helm release
  # Type: string
  name = values.name # TODO: fill in value

  # Description: The repository of the helm chart
  # Type: string
  repository = values.repository # TODO: fill in value

  # Description: The chart of the helm chart
  # Type: string
  chart = values.chart # TODO: fill in value


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: The tags to add to the helm release
  # Type: map
  tags = try(values.tags, {})

}
